server:
  port: 8762
spring:
  application:
    name: configeserver
  profiles:
    # 配置文件的获取方式：读取本地还是远程仓库；native本地
    active: native
  cloud:
    config:
      server:
        native:
          # 本地配置文件的存储地址
          search-locations: classpath:/shared